"""create task and task watchers tables

Revision ID: 5e532e663be7
Revises: 
Create Date: 2025-09-04 20:51:25.841765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e532e663be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('author_deleted', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=True),
    sa.Column('operator_deleted', sa.Boolean(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'todo', 'in_progress', 'done')", name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_task_author'), 'task', ['author'], unique=False)
    op.create_index(op.f('ix_task_operator'), 'task', ['operator'], unique=False)
    op.create_table('task_watcher',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_index(op.f('ix_task_watcher_user_id'), 'task_watcher', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_watcher_user_id'), table_name='task_watcher')
    op.drop_table('task_watcher')
    op.drop_index(op.f('ix_task_operator'), table_name='task')
    op.drop_index(op.f('ix_task_author'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
